from __future__ import annotations

from typing import Protocol

from egtsr_runtime.models import (
    Assertion,
    AttemptFamily,
    Capsule,
    Event,
    Evidence,
    InvalidationTicket,
    Obligation,
    RepoState,
    Session,
    VerifyResult,
)


class SessionRepository(Protocol):
    def create(self, session: Session) -> None: ...
    def get(self, session_id: str) -> Session | None: ...
    def update(self, session: Session) -> None: ...


class RepoStateRepository(Protocol):
    def get(self, session_id: str) -> RepoState | None: ...
    def upsert(self, repo_state: RepoState) -> None: ...
    def mark_dirty(self, session_id: str, changed_files: list[str], last_scan_at: str) -> None: ...
    def clear_dirty(self, session_id: str, last_scan_at: str) -> None: ...


class ObligationRepository(Protocol):
    def get(self, obligation_id: str) -> Obligation | None: ...
    def list_for_session(self, session_id: str) -> list[Obligation]: ...
    def list_open(self, session_id: str) -> list[Obligation]: ...
    def list_open_ids(self, session_id: str) -> list[str]: ...
    def list_by_ids_ordered(self, session_id: str, obligation_ids: list[str]) -> list[Obligation]: ...
    def bulk_mark_reopened(self, obligation_ids: list[str], updated_at: str) -> None: ...
    def upsert(self, obligation: Obligation) -> None: ...
    def mark_status(self, obligation_id: str, status: str) -> None: ...


class EvidenceRepository(Protocol):
    def create(self, evidence: Evidence) -> None: ...
    def get(self, evidence_id: str) -> Evidence | None: ...
    def list_by_ids(self, evidence_ids: list[str]) -> list[Evidence]: ...
    def bulk_create(self, evidence_items: list[Evidence]) -> None: ...
    def list_for_session(self, session_id: str) -> list[Evidence]: ...


class AssertionRepository(Protocol):
    def get(self, assertion_id: str) -> Assertion | None: ...
    def list_for_session(self, session_id: str) -> list[Assertion]: ...
    def list_by_ids(self, assertion_ids: list[str]) -> list[Assertion]: ...
    def list_active_by_obligation_ids(self, obligation_ids: list[str]) -> list[Assertion]: ...
    def bulk_upsert(self, assertions: list[Assertion]) -> None: ...
    def bulk_mark_stale(self, assertion_ids: list[str], updated_at: str) -> None: ...
    def list_obligation_ids_for_assertions(self, assertion_ids: list[str]) -> list[str]: ...
    def upsert(self, assertion: Assertion) -> None: ...


class InvalidationRepository(Protocol):
    def get(self, ticket_id: str) -> InvalidationTicket | None: ...
    def list_for_session(self, session_id: str) -> list[InvalidationTicket]: ...
    def list_live_for_assertions(self, assertion_ids: list[str]) -> list[InvalidationTicket]: ...
    def list_live_for_obligations(self, obligation_ids: list[str]) -> list[InvalidationTicket]: ...
    def bulk_upsert(self, tickets: list[InvalidationTicket]) -> None: ...
    def upsert(self, ticket: InvalidationTicket) -> None: ...


class AttemptFamilyRepository(Protocol):
    def get(self, family_id: str) -> AttemptFamily | None: ...
    def list_for_session(self, session_id: str) -> list[AttemptFamily]: ...
    def get_by_signature(self, session_id: str, signature: str) -> AttemptFamily | None: ...
    def list_recent_failures_by_obligation_ids(
        self, obligation_ids: list[str], limit_per_obligation: int = 5
    ) -> list[AttemptFamily]: ...
    def upsert(self, family: AttemptFamily) -> None: ...


class VerifyRepository(Protocol):
    def create(self, result: VerifyResult) -> None: ...
    def get(self, result_id: str) -> VerifyResult | None: ...
    def list_for_session(self, session_id: str) -> list[VerifyResult]: ...


class CapsuleRepository(Protocol):
    def create(self, capsule: Capsule) -> None: ...
    def get(self, capsule_id: str) -> Capsule | None: ...
    def list_for_session(self, session_id: str) -> list[Capsule]: ...


class EventRepository(Protocol):
    def create(self, event: Event) -> None: ...
    def get(self, event_id: str) -> Event | None: ...
    def list_for_session(self, session_id: str) -> list[Event]: ...
